{% set version = "1.5.3" %}
{% set sha256 = "b07d17fea577f5719d4346dde3182fd86778786d062ee135d122d8f75ac7b3ff" %}

package:
  name: cymetric
  version: {{ version }}

source:
  fn: cymetric-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cymetric/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --prefix ${PREFIX}

requirements:
  build:
    - python
  run:
    - python
    - cyclus >=1.5.*
    #- pyne  # this is working locally, but not on conda-forge for some weird reason
    - numpy
    - pandas
    - pytables
    - python-graphviz

test:
  imports:
    - cymetric

about:
  home: http://fuelcycle.org
  license: BSD 3-clause
  license_family: BSD
  summary: 'Cyclus Metrics'
  doc_url: http://fuelcycle.org/user/cymetric/index.html
  dev_url: https://github.com/cyclus/cymetric

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
