{% set version = "1.5.3" %}
{% set org = "cyclus" %}
{% set branch = "1.5.0" %}
{% set sha256 = "b07d17fea577f5719d4346dde3182fd86778786d062ee135d122d8f75ac7b3ff" %}

package:
  name: cymetric
  version: {{ version }}

source:
  fn: cymetric-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cymetric/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py34]
  script: python setup.py install --prefix ${PREFIX}

requirements:
  build:
    - python
  run:
    - python
    - cyclus >=1.5.*
    - pandas

test:
  requires:
    - cycamore >=1.5.*
    - nose
  # Remove the following when conda-forge migrates to conda-build v2.*
  imports:
    - cymetric
  # Use the following when conda-forge migrates to conda-build v2.*
  #commands:
  #  - cd "${SRC_DIR}/tests"
  #  - nosetests test_cyclus.py test_evaluator.py test_fco_metrics.py test_root_metrics.py  # [py27]
  #  - nosetests  # [py35]

about:
  home: http://fuelcycle.org
  license: BSD 3-clause
  license_family: BSD
  summary: 'Cyclus Metrics'
  doc_url: http://fuelcycle.org/user/cymetric/index.html
  dev_url: https://github.com/cyclus/cymetric

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
