travis:
  secure:
    BINSTAR_TOKEN: rXrTwkQeeXK+J5VK0eUmVH/Xd4eKOYCLz0KN0EN8vtCZ+GcxnKMnyZihtx4MR7dRMBD2YBW0OcshGkoERKMwe0quYRmNQc61AvbjTbPMAYcEFDswsqI8f6ZdrFQpCw/Jojsfnouj/vzEDv9fbmTfxwGrXBPxPz5cOq0COlAKQ2dv4JGiPUXFUg/g5Kq6XZH25HLbQPadNizY0y6bhTIn8dvsAOlrJkpy6lcNtzUXjlBX782g3iHGYVsuSW5bXRePGFu5vq8Vh8rd1NA4feDKgjZIXRDkfGJGLF8zEtdZp9YbCxUZ+H/R/M19ydZUM6IFaAOeBssQ/gTmoCcSeVhB9mS2U7P+4gaSsF+2iMScj806+zeyWPgQNz9+Qx/0C+cYtJ5CjR+eSqzFTJy7ePpFcXAPuJgg9URiqdftIIKMRwtpE2t6PBStK6A3Zp6AtVgreR8J3cj/75TNgNUUFWSrcMNCo+BjQYWTofl8RLRYGHpwRM0e1jgvXn8pUp8w8/STB71/kH7dLMt53cEQ5Gyl3wPJDqjJPJFGgxJn76Wh+xVV3oOuDCzVqtIMZBuKq36Og0E+yDcb7QbY8uMZ9hJfhoFI2azRIWvkYk2PMgWUOOz3HDGLbgeVf/EV3Ai8OTEXlOpiB3bjEgkzsHvbcM0Tgzt/E6skwHYr8ziFmI9hP2A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
